```{r setup, include=FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

library(here) #easy file paths
library(tidyverse) #data wrangling
library(tidymodels) #modeling
library(tidyclust)
library(patchwork)

set.seed(42) #set random seed
```

#### Data Cleaning

Today, we are going to use the top 3 habitats and take a random sample of 500, then select trophic level and length for clustering

```{r}

fish_clean = read_csv(here("week_8", "data", "fish_clean.csv")) %>% 
  mutate(habitat = as.factor(habitat)) %>% 
  filter(habitat %in% c("reef-associated", "demersal", "benthopelagic")) %>% 
  sample_n(500)

fish_clust = fish_clean %>% 
  select(trophic_level_impute, length_impute) 

lapply(fish_clust, class)

```

### Clustering

```{r}
folds <- vfold_cv(fish_clust, v = 5)
```

#### KMeans

```{r}
kmeans_spec <- k_means(num_clusters = tume()) %>% 
  set_engine("stats")
```

```{r}
recipe <- recipe(~., data = fish_clust) %>% 
  step_normalized(all_predictors())

kmeans_wflow <- workflow(recipe, kmeans_spec)
```

```{r}
clust_num_grid <- grid_regular(num_clusters(), 
                               levels = 10)
```

```{r}
res <- tune_cluster(
  kmeans_wflow,
  resamples = folds,
  grid = clust_num_grid,
  control = control_grid(save_pred = TRUE, extract = identity),
  metrics = cluster_metric_set(sse_within_total, sse_total, sse_ratio)
)
```

```{r}
res_metrics <- res %>% collect_metrics()
res_metrics
```

```{r}
res_metrics %>%
  filter(.metric == "sse_ratio") %>%
  ggplot(aes(x = num_clusters, y = mean)) +
  geom_point() +
  geom_line() +
  theme_bw() +
  ylab("mean WSS/TSS ratio, over 5 folds") +
  xlab("Number of clusters") +
  scale_x_continuous(breaks = 1:10)
```

```{r}
kmeans_spec1 <- kmeans(num_clusters = 4) %>% 
  set_engine("stats")

kmeans_wflow1 <- workflow(recipe, kmeans_spec1)
```

```{r}
kmeans_fit1 <- kmeans_wflow1 %>% 
  fit(data = fish_clust)
kmeans_fit1

#in this equation, we looking at between_ss (between clusters) and we want this to be big as possible (the percentage)
#but when replaced with within, we want to be smaller (the percentage)
```

```{r}
kmeans_spec2 <- kmeans(num_clusters = 5) %>% 
  set_engine("stats")

kmeans_wflow2 <- workflow(recipe, kmeans_spec2)
```

```{r}
kmeans_fit2 <- kmeans_wflow2 %>% 
  fit(data = fish_clust)
kmeans_fit2
```

```{r}
kmeans_fit1 %>% 
  silhouette_ave(fish_clust)
```

```{r}
kmeans_fit2 %>% 
  silhouette_ave(fish_clust)
```
This silhouette number means that higher is better. combines within and total better than the ratio. if we see negative values, that point should have been in another cluster.

```{r}
clusters <- kmeans_fit1 %>% 
  extract_cluster_assignment()

fish_clean$cluster <- clusters$.cluster
```

```{r}
ggplot(fish_clean) +
  geom_point(aes(trphic_level_impute, length_impute, color = cluster)) +
  theme_bw() +
  scale_color_viridis_d()

ggplot(fish_clean) +
  geom_point(aes(trphic_level_impute, length_impute, color = habitat, shape = cluster)) +
  theme_bw() +
  scale_color_viridis_d()
```

#### Heirarchical Clustering

```{r}
hc_spec <- hier_clust(
  linkage_method = "average"
)
```

```{r}
hc_fit <- hc_spec %>% 
  fit(~., data = fish_clean)
```

```{r}
hc_fit$fit %>% 
  plot()
```

